services:
  barni-assistant:
    build:
      context: .
      args:
        BUILDKIT_INLINE_CACHE: "1"
    container_name: barni-assistant
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
